version: '3.8'

services:
  django_app:
    build: .
    container_name: django_icsg7
    restart: unless-stopped
    
    # --- SECCIÓN 'ports' ELIMINADA ---
    # Traefik se encarga de esto. No es necesario publicar
    # el puerto 8000 en el host.
    
    networks:
      # Conectado directamente a la red externa
      - proxy_network
      
    ports:
      - "8000:8000"  # Mapea el puerto 8000 del contenedor al puerto 8000 del host
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.n8n.rule=Host(`icsg7.tvergara.cc`)"
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.services.n8n.loadbalancer.server.port=8000"

networks:
  # Definición de red simplificada
  proxy_network:
    external: true