version: '3.8'

services:
  django_app:
    build: .
    container_name: django_icsg7
    restart: unless-stopped
    
    # --- SECCIÓN 'ports' ELIMINADA ---
    # Traefik se encarga de esto. No es necesario publicar
    # el puerto 8000 en el host.
    
    networks:
      # Conectado directamente a la red externa
      - proxy_network
      
    ports:
      - "8000:8000"  # Mapea el puerto 8000 del contenedor al puerto 8000 del host
    labels:
      - "traefik.enable=true"
      
      # --- Router HTTP ---
      - "traefik.http.routers.django-icsg7-router.rule=Host(`icsg7.tevergara.cc`)"
      - "traefik.http.routers.django-icsg7-router.entrypoints=web"
      
      # --- ¡AQUÍ ESTÁ LA LÍNEA QUE FALTABA! ---
      # Esta línea conecta el Router al Servicio
      - "traefik.http.routers.django-icsg7-router.service=django-icsg7-service"

      # --- Servicio ---
      # (Tu definición del servicio estaba perfecta)
      - "traefik.http.services.django-icsg7-service.loadbalancer.server.port=8000"

networks:
  # Definición de red simplificada
  proxy_network:
    external: true