version: '3.8'

services:
  # Este es el nombre de tu servicio
  django_app:
    # Construye la imagen usando el Dockerfile en el directorio actual (.)
    build: .
    # Asigna un nombre de contenedor para identificarlo fácilmente
    container_name: django_icsg7
    # Reinicia siempre el contenedor si falla
    restart: always
    # Conecta el contenedor a la red 'proxy'
    networks:
      - proxy
    # Etiquetas (labels) para que Traefik configure el enrutamiento
    labels:
      - "traefik.enable=true"
      # --- Router HTTP ---
      # Define la regla de enrutamiento: Peticiones al host 'icsg7.tevergara.cc'
      - "traefik.http.routers.django-icsg7-router.rule=Host(`icsg7.tevergara.cc`)"
      # Especifica el punto de entrada (entrypoint), usualmente 'websecure' para HTTPS
      - "traefik.http.routers.django-icsg7-router.entrypoints=web"
      # --- Servicio ---
      # Define cómo Traefik debe conectarse a tu servicio
      # 'django-icsg7-service' es solo un nombre interno para Traefik
      - "traefik.http.services.django-icsg7-service.loadbalancer.server.port=8000"

networks:
  # Define la red 'proxy'
  proxy:
    # Le dice a Docker Compose que esta red ya existe y es gestionada
    # externamente (probablemente por Traefik)
    external: true
    name: proxy_network